[build]
  command = "echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src-elem 'unsafe-inline' 'self' connect.facebook.net pagead2.googlesyndication.com unpkg.com www.googletagmanager.com d33wubrfki0l68.cloudfront.net adservice.google.com adservice.google.nl partner.googleadservices.com tpc.googlesyndication.com www.google-analytics.com www.googletagservices.com gimmix.disqus.com maps.googleapis.com www.google.com c.disquscdn.com www.gstatic.com adservice.google.com.pk adservice.google.ca cdn.ampproject.org; script-src 'unsafe-eval' 'self' d33wubrfki0l68.cloudfront.net pagead2.googlesyndication.com unpkg.com 'unsafe-inline' adservice.google.com adservice.google.nl connect.facebook.net gimmix.disqus.com maps.googleapis.com partner.googleadservices.com tpc.googlesyndication.com www.google.com www.googletagmanager.com www.googletagservices.com c.disquscdn.com www.google-analytics.com www.gstatic.com adservice.google.de; worker-src 'self'; connect-src pagead2.googlesyndication.com 'self' analytics.google.com stats.g.doubleclick.net www.google-analytics.com www.google.nl www.facebook.com links.services.disqus.com; frame-src googleads.g.doubleclick.net www.facebook.com open.spotify.com tpc.googlesyndication.com www.google.com disqus.com pagead2.googlesyndication.com; img-src i.postimg.cc pagead2.googlesyndication.com 'self' data: www.google-analytics.com c.disquscdn.com feedburner.google.com images.ctfassets.net maps.googleapis.com maps.gstatic.com referrer.disqus.com s3.feedly.com www.facebook.com www.google.nl www.google.com www.googletagmanager.com; prefetch-src adservice.google.com cdnjs.cloudflare.com connect.facebook.net pagead2.googlesyndication.com partner.googleadservices.com unpkg.com www.google-analytics.com www.googletagmanager.com www.googletagservices.com adservice.google.nl c.disquscdn.com disqus.com adservice.google.ca; style-src-elem cdnjs.cloudflare.com fonts.googleapis.com 'unsafe-inline'; font-src data: fonts.gstatic.com; style-src cdnjs.cloudflare.com fonts.googleapis.com 'unsafe-eval' 'unsafe-inline'; style-src-attr 'unsafe-inline'; 'upgrade-insecure-requests; block-all-mixed-content; object-src 'self'; manifest-src 'self'; report-uri https://gimmix.report-uri.com/r/d/csp/wizard; report-to default"

    Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
    X-Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
    X-WebKit-CSP-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"

    Expect-CT = 'enforce, 0, report-uri="https://gimmix.report-uri.com/r/d/ct/reportOnly"'

    Permissions-Policy = 'geolocation=(self "https://gimmix.nl/*"), microphone=(), fullscreen=(self "https://gimmix.nl/*"), camera=()'

    X-Permitted-Cross-Domain-Policies = "none"

    Referrer-Policy = "no-referrer"
    # Referrer Policy = "strict-origin-when-cross-origin"

    # Access-Control-Allow-Origin = "*"

    Cache-Control = "public, max-age=0, must-revalidate"
    # Cache-Control = "no-cache"

    # Cross-Origin-Resource-Policy = "cross-origin"

  # [[headers]]
  # for = "/*"
  # [headers.values]
  #   cache-control = '''
  #   max-age=0,
  #   no-cache,
  #   no-store,
  #   must-revalidate'''
    
  [Report-To]
    group = "default"
    max_age = 31_536_000
    include_subdomains = true

    [[Report-To.endpoints]]
      url = "https://gimmix.report-uri.com/a/d/g"

  [NEL]
    report_to = "default"
    max_age = 31_536_000
    include_subdomains = true