[build]
  command = "echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
    X-Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
    X-WebKit-CSP-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"

    Report-To = {"group":"default","max_age":31536000,"endpoints":[{"url":"https://gimmix.report-uri.com/a/d/g"}],"include_subdomains":true}

    NEL = {"report_to":"default","max_age":31536000,"include_subdomains":true}

    Expect-CT = "max-age=0, report-uri='https://gimmix.report-uri.com/r/d/ct/reportOnly';"
