[build]
  command = "echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build"
  publish = "public"


[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
    Expect-CT = "max-age=0, report-uri='https://gimmix.nl/';"