[build]
  command = "echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'report-sample' 'self' 'unsafe-eval' 'unsafe-inline' https://adservice.google.com/adsid/integrator.js https://adservice.google.nl/adsid/integrator.js https://c.disquscdn.com/next/embed/alfie.f51946af45e0b561c60f768335c9eb79.js https://connect.facebook.net/nl_NL/sdk/xfbml.customerchat.js https://d33wubrfki0l68.cloudfront.net/bundles/a800899e5eef52f8da10311a0628d8895e6309b2.js https://gimmix.disqus.com/embed.js https://links.services.disqus.com/api/click https://maps.googleapis.com/maps-api-v3/api/js/42/9/intl/nl_ALL/common.js https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js https://partner.googleadservices.com/gampad/cookie.js https://tpc.googlesyndication.com/sodar/sodar2.js https://unpkg.com/swiper/swiper-bundle.min.js https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/api.js https://www.googletagmanager.com/gtm.js https://www.googletagservices.com/activeview/js/current/osd.js https://www.gstatic.com/recaptcha/releases/4lbq4vBYAu25DMtzZ7GGbfAF/recaptcha__en.js; style-src 'unsafe-inline' 'report-sample' 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com; object-src 'none'; base-uri 'self'; connect-src 'self' https://analytics.google.com https://links.services.disqus.com https://pagead2.googlesyndication.com https://stats.g.doubleclick.net https://www.google-analytics.com https://www.google.nl; font-src 'self' data: https://fonts.gstatic.com; frame-src 'self' https://disqus.com https://googleads.g.doubleclick.net https://open.spotify.com https://tpc.googlesyndication.com https://www.facebook.com https://www.google.com; img-src 'self' data: https://feedburner.google.com https://i.postimg.cc https://images.ctfassets.net https://maps.googleapis.com https://maps.gstatic.com https://pagead2.googlesyndication.com https://s3.feedly.com https://www.facebook.com https://www.google-analytics.com https://www.google.com https://www.google.nl; manifest-src 'self'; media-src 'self'; prefetch-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://maps.googleapis.com https://unpkg.com; report-uri https://5f9cae8b65d1a16209ba9064.endpoint.csper.io/; worker-src 'self';"
    

    # report-uri https://gimmix.report-uri.com/r/d/csp/wizard; report-to default"

#     Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
#     X-Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
#     X-WebKit-CSP-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"

      Expect-CT = 'enforce, 0, report-uri="https://gimmix.report-uri.com/r/d/ct/reportOnly"'

      Permissions-Policy = 'geolocation=(self "https://gimmix.nl/*"), microphone=(), fullscreen=(self "https://gimmix.nl/*"), camera=()'

#     X-Permitted-Cross-Domain-Policies = "none"

#     Referrer-Policy = "no-referrer"
    
#   [Report-To]
#     group = "default"
#     max_age = 31_536_000
#     include_subdomains = true

#     [[Report-To.endpoints]]
#       url = "https://gimmix.report-uri.com/a/d/g"

#   [NEL]
#     report_to = "default"
#     max_age = 31_536_000
#     include_subdomains = true