[build]
  command = "echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'report-sample' 'self' 'unsafe-eval' 'unsafe-inline' adservice.google.com adservice.google.nl c.disquscdn.com connect.facebook.net d33wubrfki0l68.cloudfront.net gimmix.disqus.com links.services.disqus.com maps.googleapis.com pagead2.googlesyndication.com partner.googleadservices.com tpc.googlesyndication.com unpkg.com www.google-analytics.com www.google.com www.googletagmanager.com www.googletagservices.com www.gstatic.com; style-src 'report-sample' 'self' 'unsafe-inline' cdnjs.cloudflare.com fonts.googleapis.com; object-src 'none'; base-uri 'self'; connect-src 'self' maps.gstatic.com feedburner.google.com s3.feedly.com gimmix.disqus.com images.ctfassets.net maps.googleapis.com www.gstatic.com unpkg.com fonts.gstatic.com i.postimg.cc connect.facebook.net d33wubrfki0l68.cloudfront.net cdnjs.cloudflare.com fonts.googleapis.com analytics.google.com links.services.disqus.com pagead2.googlesyndication.com stats.g.doubleclick.net www.google-analytics.com www.google.nl; font-src 'self' data: fonts.gstatic.com; frame-src 'self' disqus.com googleads.g.doubleclick.net open.spotify.com pagead2.googlesyndication.com tpc.googlesyndication.com web.facebook.com www.facebook.com www.google.com; img-src 'self' data: feedburner.google.com i.postimg.cc images.ctfassets.net maps.googleapis.com maps.gstatic.com pagead2.googlesyndication.com s3.feedly.com www.facebook.com www.google-analytics.com www.google.com www.google.nl; manifest-src 'self'; media-src 'self'; prefetch-src 'self' *.pagead2.googlesyndication.com/* partner.googleadservices.com *.adservice.google.nl/* *.adservice.google.com/* www.googletagservices.com www.googletagmanager.com www.google-analytics.com connect.facebook.net *.cdnjs.cloudflare.com/* fonts.googleapis.com maps.googleapis.com *.unpkg.com/*; report-uri https://5f9cae8b65d1a16209ba9064.endpoint.csper.io/; worker-src 'self';"
    

#   report-uri https://gimmix.report-uri.com/r/d/csp/wizard report-to default"

#     Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
#     X-Content-Security-Policy-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"
#     X-WebKit-CSP-Report-Only = "report-uri https://gimmix.report-uri.com/r/d/csp/reportOnly"

      Expect-CT = 'enforce, 0, report-uri="https://gimmix.report-uri.com/r/d/ct/reportOnly"'

      Permissions-Policy = 'geolocation=(self "https://gimmix.nl/*"), microphone=(), fullscreen=(self "https://gimmix.nl/*"), camera=()'

#     X-Permitted-Cross-Domain-Policies = "none"

#     Referrer-Policy = "no-referrer"
    
  [Report-To]
    group = "default"
    max_age = 31_536_000
    include_subdomains = true

    [[Report-To.endpoints]]
      url = "https://gimmix.report-uri.com/a/d/g"

  [NEL]
    report_to = "default"
    max_age = 31_536_000
    include_subdomains = true